heat_template_version: 2015-04-30

description: Databases topology

resources:
  identification_instance:
    type: OS::Nova::Server
    properties:
      name: "identification_database"
      image: "ubuntu1404"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "databases_network"

  status_instance:
    type: OS::Nova::Server
    properties:
      name: "status_database"
      image: "ubuntu1404"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "databases_network"