heat_template_version: 2015-04-30

description: Services topology

resources:
  i_instance:
    type: OS::Nova::Server
    properties:
      name: "i_service"
      image: "ubuntu1404"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "services_network"

  s_instance:
    type: OS::Nova::Server
    properties:
      name: "s_service"
      image: "ubuntu1404"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "services_network"

  b_instance:
    type: OS::Nova::Server
    properties:
      name: "b_service"
      image: "ubuntu1404"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "services_network"

  w_instance:
    type: OS::Nova::Server
    properties:
      name: "w_service"
      image: "ubuntu1404"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "services_network"

  p_instance:
    type: OS::Nova::Server
    properties:
      name: "p_service"
      image: "ubuntu1404"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "services_network"

  web_app_instance:
    type: OS::Nova::Server
    properties:
      name: "web_app"
      image: "ubuntu1404"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "services_network"