- name: Create service script
  copy:
    src: client_dns
    dest: /etc/init.d/client_dns
    owner: root
    group: root
    mode: 0755
  become: true

- name: Reload daemons
  command: systemctl daemon-reload
  become: true

- name: Launch dns client
  service:
    name: client_dns
    state: started
  become: true

- name: client join the cluster
  shell: consul join {% for host in groups['serveur_dns'] %}{{ hostvars[host]['ansible_default_ipv4']['address'] }}{% endfor %}
  become: true
