---
# This Playbook runs all the common plays in the deployment

# Propagate /etc/hosts file on every machine
- copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    chmod: 0644