- name: Init db ident
  mysql_db:
    state: import
    name: all
    login_user: root
    login_password: root
    target: /apps/external/dbident_init.sql
  become: true-

name: Load ident dump
  mysql_db:
    state: import
    name: all
    login_user: root
    login_password: root
    target: /apps/external/prestashop_fullcustomer.dump.sql
  become: true