heat_template_version: 2015-04-30

description: Databases topology

resources:
  #VOLUMES
  status_volume:
    type: OS::Cinder::Volume
    properties:
      availability_zone: "nova"
      description: "Volume for the status databases"
      name: "status_db_volume"
      size: 1
      volume_type: "nfs"

  identification_volume:
    type: OS::Cinder::Volume
    properties:
      availability_zone: "nova"
      description: "Volume for the identification databases"
      name: "identification_db_volume"
      size: 1
      volume_type: "nfs"

  #INSTANCE
  identification_instance:
    type: OS::Nova::Server
    properties:
      name: "identification_database"
      security_groups: ["default", "custom_group"]
      image: "ubuntu1604"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      networks:
       - network: "databases_network"
      user_data_format: SOFTWARE_CONFIG
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python


  status_instance:
    type: OS::Nova::Server
    properties:
      name: "status_database"
      image: "ubuntu1604"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      security_groups: ["default", "custom_group"]
      networks:
       - network: "databases_network"
      user_data_format: SOFTWARE_CONFIG
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python

  #VOLUME ATTACHMENT
  identification_volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: identification_instance }
      volume_id: { get_resource: identification_volume }
      mountpoint: "/dev/vdb"

  status_volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      instance_uuid: { get_resource: status_instance }
      volume_id: { get_resource: status_volume }
      mountpoint: "/dev/vdb"

#OUTPUTS
outputs:
  identification_database_private_ip:
    description: "Private IP address of the deployed compute instance"
    value: { get_attr: [identification_instance, first_address] }

  status_database_private_ip:
    description: "Private IP address of the deployed compute instance"
    value: { get_attr: [status_instance, first_address] }