heat_template_version: '2015-04-30'
description: Services topology
resources:
  custom_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Custom security
      name: custom_group
      rules:
      - {direction: ingress, ethertype: IPv4, port_range_max: 22, port_range_min: 22,
        protocol: tcp, remote_ip_prefix: 0.0.0.0/0, remote_mode: remote_ip_prefix}
      - {direction: ingress, ethertype: IPv4, port_range_max: 80, port_range_min: 80,
        protocol: tcp, remote_ip_prefix: 0.0.0.0/0, remote_mode: remote_ip_prefix}
      - {direction: ingress, ethertype: IPv4, protocol: icmp, remote_ip_prefix: 0.0.0.0/0,
        remote_mode: remote_ip_prefix}
      - {direction: ingress, ethertype: IPv4, port_range_max: 3306, port_range_min: 3306,
        protocol: tcp, remote_ip_prefix: 10.0.7.0/24, remote_mode: remote_ip_prefix}