heat_template_version: 2015-04-30

description: Services topology

resources:

  # FLOATING IP ADDRESS
  web_app_floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: external-network

  #INSTANCE
  i_instance:
    type: OS::Nova::Server
    properties:
      name: "service_i"
      image: "ubuntu1604"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      security_groups: ["default", "custom_group"]
      networks:
       - network: "services_network"
      user_data_format: SOFTWARE_CONFIG
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python

  s_instance:
    type: OS::Nova::Server
    properties:
      name: "service_s"
      image: "ubuntu1604"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      security_groups: ["default", "custom_group"]
      networks:
       - network: "services_network"
      user_data_format: SOFTWARE_CONFIG
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python

  b_instance:
    type: OS::Nova::Server
    properties:
      name: "service_b"
      image: "ubuntu1604"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      security_groups: ["default", "custom_group"]
      networks:
       - network: "services_network"
      user_data_format: SOFTWARE_CONFIG
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python

  w_instance:
    type: OS::Nova::Server
    properties:
      name: "service_w"
      image: "ubuntu1604"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      security_groups: ["default", "custom_group"]
      networks:
       - network: "services_network"
      user_data_format: SOFTWARE_CONFIG
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python

  p_instance:
    type: OS::Nova::Server
    properties:
      name: "service_p"
      image: "ubuntu1604"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      security_groups: ["default", "custom_group"]
      networks:
       - network: "services_network"
      user_data_format: SOFTWARE_CONFIG
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python

  web_app_instance:
    type: OS::Nova::Server
    properties:
      name: "web_app"
      image: "ubuntu1604"
      flavor: "m1.small"
      key_name: "default-rsa-key"
      security_groups: ["default", "custom_group"]
      networks:
       - network: "services_network"
      user_data_format: SOFTWARE_CONFIG
      user_data: |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y python

  # FLOATING IP ASSOCIATION
  wab_app_floating_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: web_app_floating_ip }
      server_id: { get_resource: web_app_instance }

#OUTPUTS
outputs:
  service_i_private_ip:
    description: "Private IP address of the deployed compute instance"
    value: { get_attr: [i_instance, first_address] }

  service_s_private_ip:
    description: "Private IP address of the deployed compute instance"
    value: { get_attr: [s_instance, first_address] }

  service_b_private_ip:
    description: "Private IP address of the deployed compute instance"
    value: { get_attr: [b_instance, first_address] }

  service_w_private_ip:
    description: "Private IP address of the deployed compute instance"
    value: { get_attr: [w_instance, first_address] }

  service_p_private_ip:
    description: "Private IP address of the deployed compute instance"
    value: { get_attr: [p_instance, first_address] }

  web_app_private_ip:
    description: "Private IP address of the deployed compute instance"
    value: { get_attr: [web_app_instance, first_address] }

  web_app_floating_ip:
    description: "Floating IP address of the deployed compute instance"
    value: { get_attr: [web_app_floating_ip, ip] }