#!/bin/sh
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      $portmap
# Should-Stop:       $portmap
# X-Start-Before:    nis
# X-Stop-After:      nis
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

DAEMON="/usr/local/bin/consul"
DAEMONUSER="root"
daemon_NAME="client_dns"
daemon_OPT="agent -data-dir=/tmp/consul -config-dir=/etc/consul.d -dns-port=53 "

PATH="/sbin:/bin:/usr/sbin:/usr/bin"

case "$1" in
  start)
        start-stop-daemon --background --name $daemon_NAME --start --quiet --chuid $DAEMONUSER --exec $DAEMON -- $daemon_OPT
        ;;
  stop)
        start-stop-daemon --name $daemon_NAME --stop --retry 5 --quiet
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
