- name: Install python package keystoneauth1
  pip:
    name: keystoneauth1
    executable: pip3
  become: true

- name: Install python package python-keystoneclient
  pip:
    name: python-keystoneclient
    executable: pip3
  become: true

- name: Install python package python-swiftclient
  pip:
    name: python-swiftclient
    executable: pip3
  become: true

- name: Configure service to launch b service
  shell: echo "services/b/b" > /etc/init.d/service.conf
  become: true

- name: Launch B service
  service:
    name: sombrero
    state: started
  become: true