- name: launch server
  command: consul agent -server -bootstrap-expect=1 -data-dir=/tmp/consul -node="{{ inventory_hostname }}" -bind="{{ ansible_default_ipv4.address }}"  -config-dir=/etc/consul.d &
  become: true