- name: Create service script
  copy:
    src: serveur_dns
    dest: /etc/init.d/serveur_dns
    owner: root
    group: root
    mode: 0755
  become: true

- name: Reload daemons
  command: systemctl daemon-reload
  become: true

- name: Launch dns server
  service:
    name: serveur_dns
    state: started
  become: true
