- name: Install python package pymysl
  pip:
    name: pymysql
    executable: pip3
  become: true

- name: Configure service to launch s service
  command: echo "services/s/s" > /etc/init.d/service.conf

- name: Launch S service
  service:
    name: sombrero_service
    state: started
  become: true